import type { Question } from '../types/survey';

export const questions: Question[] = [
  {
    id: 'age',
    title: 'Patient Age',
    description: 'Enter your age in years',
    type: 'number',
    min: 0,
    max: 120,
    required: true,
  },
  {
    id: 'sex',
    title: 'Patient Gender',
    description: 'Select your gender',
    type: 'radio',
    options: [
      { value: 0, label: 'Female' },
      { value: 1, label: 'Male' },
      { value: 3, label: 'Other' },
    ],
    required: true,
  },
  {
    id: 'cp',
    title: 'Chest Pain Type',
    description: 'Select the type of chest pain you experience',
    type: 'select',
    options: [
      { value: 0, label: 'Typical Angina' },
      { value: 1, label: 'Atypical Angina' },
      { value: 2, label: 'Non-Cardiac Pain' },
      { value: 3, label: 'Asymptomatic' },
    ],
  },
  {
    id: 'trestbps',
    title: 'Resting Blood Pressure',
    description: 'Enter your systolic blood pressure in mmHg',
    type: 'number',
    min: 90,
    max: 200,
  },
  {
    id: 'chol',
    title: 'Cholesterol Level',
    description: 'Enter your blood cholesterol level in mg/dl',
    type: 'number',
    min: 100,
    max: 600,
  },
  {
    id: 'fbs',
    title: 'Fasting Blood Sugar',
    description: 'Is your blood sugar greater than 120 mg/dl?',
    type: 'radio',
    options: [
      { value: 0, label: 'Less than 120 mg/dl' },
      { value: 1, label: 'Greater than 120 mg/dl' },
    ],
  },
  {
    id: 'restecg',
    title: 'Resting ECG Results',
    description: 'Select the result of your resting electrocardiogram',
    type: 'select',
    options: [
      { value: 0, label: 'Normal' },
      { value: 1, label: 'ST-T wave abnormality' },
      { value: 2, label: 'Left ventricular hypertrophy' },
    ],
  },
  {
    id: 'thalach',
    title: 'Maximum Heart Rate',
    description: 'Enter your maximum heart rate during exercise',
    type: 'number',
    min: 70,
    max: 200,
  },
  {
    id: 'exang',
    title: 'Exercise-Induced Angina',
    description: 'Do you experience angina during physical activity?',
    type: 'radio',
    options: [
      { value: 0, label: 'No' },
      { value: 1, label: 'Yes' },
    ],
  },
  {
    id: 'oldpeak',
    title: 'ST Depression',
    description: 'ST depression induced by exercise relative to rest',
    type: 'number',
    min: 0,
    max: 6,
    step: 0.1,
  },
  {
    id: 'slope',
    title: 'ST Segment Slope',
    description: 'Slope of the peak exercise ST segment',
    type: 'select',
    options: [
      { value: 0, label: 'Upsloping' },
      { value: 1, label: 'Flat' },
      { value: 2, label: 'Downsloping' },
    ],
  },
  {
    id: 'ca',
    title: 'Major Vessels',
    description: 'Number of major vessels colored by fluoroscopy',
    type: 'select',
    options: [
      { value: 0, label: '0 vessels' },
      { value: 1, label: '1 vessel' },
      { value: 2, label: '2 vessels' },
      { value: 3, label: '3 vessels' },
      { value: 4, label: '4 vessels' },
    ],
  },
  {
    id: 'thal',
    title: 'Thalassemia Test',
    description: 'Result of the thalassemia test',
    type: 'select',
    options: [
      { value: 0, label: 'Unknown' },
      { value: 1, label: 'Normal' },
      { value: 2, label: 'Fixed defect' },
      { value: 3, label: 'Reversible defect' },
    ],
  },
  {
    id: 'pulse',
    title: 'Resting Pulse',
    description: 'Enter your resting pulse in beats per minute',
    type: 'number',
    min: 40,
    max: 200,
  },
];
